// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arluwakftvvbioprdsmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFybHV3YWtmdHZ2YmlvcHJkc213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTg0NjksImV4cCI6MjA2ODg3NDQ2OX0.U04eUjAeBgBEPa5L0rpudKv5CP4haZUGwb916Sgx0t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});